# Generated by Django 5.0.3 on 2024-03-15 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("companyid", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
                ("contactnum", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("orderid", models.IntegerField(primary_key=True, serialize=False)),
                ("userid", models.IntegerField()),
                ("orddate", models.CharField(max_length=45)),
                ("deliverydate", models.CharField(max_length=45)),
                ("status", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="OrderAddress",
            fields=[
                ("ordaddid", models.IntegerField(primary_key=True, serialize=False)),
                ("userid", models.IntegerField()),
                ("orderaddcol", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("userid", models.IntegerField(primary_key=True, serialize=False)),
                ("phonenumber", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                ("userid", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Bottle",
            fields=[
                ("bottleid", models.IntegerField(primary_key=True, serialize=False)),
                ("price", models.CharField(max_length=45)),
                ("stock", models.CharField(max_length=45)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="supply.company"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("userid", "phonenumber"), name="user_primary_key"
            ),
        ),
    ]
